Readme
ryotaro-kohara/chat-space pull request #1
Opened 2019-05-05 11:49 UTC by ryotaro-kohara

# what
テーブル、カラムの作成
# why
DBの作成のため

2019-05-05 11:58 UTC, yuki-uchida requested changes

2019-05-05 11:58 UTC, yuki-uchida commented on README.md
> +|id|integer|null: false|
idは必ず存在するのでわざわざ書かなくて結構です！

2019-05-05 11:58 UTC, yuki-uchida commented on README.md
> +|tweet_id|integer|null: false, foreign_key: true|
外部キー制約をつけたい場合にはrefference型としましょう

2019-05-05 11:58 UTC, yuki-uchida commented on README.md
> +|name|varchar(100)|null: false|
tweetのnameよりもtweetのtextやbodyの方がわかりやすいでしょう

2019-05-05 12:35 UTC, yuki-uchida requested changes

2019-05-05 12:35 UTC, yuki-uchida commented on README.md
> +|tweet|refference|null: false, foreign_key: true|
usersテーブルとtweetsテーブルはどのような関係ですか？
このカラムが必要かどうかもう一度考えて見ましょう

2019-05-05 12:51 UTC, ghost requested changes

2019-05-05 12:51 UTC, hiroki5123 commented on README.md
> +## tweetsテーブル
ツイッターを作るわけではないので、メッセージのほうがいいかと思います。

2019-05-05 12:51 UTC, hiroki5123 commented on README.md
> +- has_many :tweets
アソシエーションが一つ足りないので見直してみましょう

2019-05-05 12:51 UTC, hiroki5123 commented on README.md
> +- has_many :user, through: :users_groups
アソシエーションが一つ足りないので見直してみましょう

2019-05-06 02:02 UTC, yuki-uchida approved these changes
LGTMです。お疲れ様でした

2019-05-10 06:38 UTC, ryotaro-kohara commented
# WHAT
messageコントローラのindexアクションの画面作成
# WHY
フロントの作成のため

# Other
ブランチを切り忘れて、DBと同じブランチで行ってしまいました。
テンプレートの量もかなり多くなってしまいました。

2019-05-10 07:01 UTC, ryotaro-kohara commented
# 上記の画像
<img width="1440" alt="スクリーンショット 2019-05-10 15 56 27" src="https://user-images.githubusercontent.com/50223422/57508512-9fef4180-733c-11e9-83be-f8a525f71166.png">

2019-05-10 07:04 UTC, TOMARUMARU commented
コミットを戻してDB設計完了の時点でこちらのPRはmergeしてください。
その後別ブランチで新たなPRを作成してください

2019-05-10 08:10 UTC, merged